version: '3.7'

services:

  postgres:
    container_name: ${TRANSACTION_DB_CONTAINER_NAME}
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${TRANSACTION_DB_PASS}
      POSTGRES_USER: ${TRANSACTION_DB_USER}
    image: postgres:13.3-alpine
    restart: unless-stopped
    ports:
      - ${TRANSACTION_DB_PORT_EXTERNAL}:5432
    networks:
      - recruitment_app_net
    volumes:
      - ./docker/POSTGRES/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  recruitment_app_net:
    name: recruitment_app_net
